---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-ui-app
  name: web-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui-app
  template:
    metadata:
      labels:
        app: web-ui-app
    spec:
      containers:
      - image: 556838424422.dkr.ecr.us-east-1.amazonaws.com/web-ui-app:$Select_Docker_image_to_Deploy
        imagePullPolicy: Always
        name: web-ui-app

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-ui-app
  name: web-ui-app
spec:
  ports:
#  - nodePort: 32223
#    port: 8080
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-ui-app
#  type: NodePort
  type: LoadBalancer
